### PR TITLE
Add i2p and tor modules

### PR DESCRIPTION
**Pull request by chimp1984**
Based on https://github.com/bisq-network/misq/pull/6

Adds Tor and I2P implementation used as socksproxy for the network connections.
Working implementation but Tor module will require more work to get it feature complete and more testing on diff. OS. @cd2357 might be working on that. So if any dev want to pick that task best to check out with @cd2357 first.

### CODE REVIEW

**Comment by chimp1984** [comment]
Merged other PRs and rebased....

**Review by jmacxx — APPROVED** [review]
utACK

**Comment by ghubstan** [comment]
utACK

**Review by jmacxx — APPROVED** [review]
utACK

**Pull request merged**
